-- Insertion de 300 motos dans la base de données
INSERT INTO VEHICULE (MARQUE, MODELE) VALUES 
('Yamaha', 'MT-07'),
('Yamaha', 'Tracer 9'),
('Yamaha', 'XSR700'),
('Yamaha', 'R1'),
('Yamaha', 'Ténéré 700'),
('Yamaha', 'FZ-09'),
('Yamaha', 'MT-09'),
('Yamaha', 'YZF-R7'),
('Yamaha', 'MT-03'),
('Yamaha', 'FJR1300'),
('Honda', 'CB650R'),
('Honda', 'CBR500R'),
('Honda', 'Africa Twin'),
('Honda', 'Rebel 500'),
('Honda', 'NC750X'),
('Honda', 'CB500F'),
('Honda', 'PCX 160'),
('Honda', 'CB400SF'),
('Honda', 'CTX700'),
('Honda', 'Gold Wing'),
('Kawasaki', 'Z900'),
('Kawasaki', 'Ninja 650'),
('Kawasaki', 'Versys 650'),
('Kawasaki', 'Z1000'),
('Kawasaki', 'Vulcan S'),
('Kawasaki', 'Z650'),
('Kawasaki', 'Ninja 400'),
('Kawasaki', 'KLR650'),
('Kawasaki', 'W800'),
('Kawasaki', 'Concours 14'),
('Suzuki', 'GSX-S750'),
('Suzuki', 'GSX-R1000'),
('Suzuki', 'V-Strom 650'),
('Suzuki', 'SV650'),
('Suzuki', 'Hayabusa'),
('Suzuki', 'GSX-S1000'),
('Suzuki', 'Boulevard C90'),
('Suzuki', 'DR650SE'),
('Suzuki', 'GSXR600'),
('Suzuki', 'SFV650'),
('BMW', 'R1250GS'),
('BMW', 'S1000RR'),
('BMW', 'F900R'),
('BMW', 'R nineT'),
('BMW', 'G310GS'),
('BMW', 'R1250RT'),
('BMW', 'F850GS'),
('BMW', 'R1200RT'),
('BMW', 'R nineT Scrambler'),
('BMW', 'C400X'),
('Ducati', 'Monster 821'),
('Ducati', 'Panigale V4'),
('Ducati', 'Scrambler Icon'),
('Ducati', 'Multistrada V4'),
('Ducati', 'Diavel 1260'),
('Ducati', 'Streetfighter V4'),
('Ducati', 'Hypermotard 950'),
('Ducati', 'Supersport 950'),
('Ducati', 'Panigale 959'),
('Ducati', 'Xdiavel'),
('KTM', 'Duke 390'),
('KTM', 'Duke 890'),
('KTM', '1290 Super Duke R'),
('KTM', '390 Adventure'),
('KTM', '690 SMC R'),
('KTM', '1190 Adventure R'),
('KTM', '390 Duke'),
('KTM', '250 Duke'),
('KTM', '790 Duke'),
('KTM', '1290 Adventure'),
('Triumph', 'Street Triple 765'),
('Triumph', 'Bonneville T120'),
('Triumph', 'Tiger 900'),
('Triumph', 'Speed Twin 900'),
('Triumph', 'Rocket 3 R'),
('Triumph', 'Trident 660'),
('Triumph', 'Scrambler 1200'),
('Triumph', 'Tiger 1200'),
('Triumph', 'Thruxton R'),
('Triumph', 'Bobber TFC'),
('Harley-Davidson', 'Iron 883'),
('Harley-Davidson', 'Sportster S'),
('Harley-Davidson', 'Street Bob 114'),
('Harley-Davidson', 'Road Glide'),
('Harley-Davidson', 'Electra Glide'),
('Harley-Davidson', 'Pan America 1250'),
('Harley-Davidson', 'Softail Slim'),
('Harley-Davidson', 'Street Glide'),
('Harley-Davidson', 'Heritage Classic'),
('Harley-Davidson', 'Breakout 117'),
('Aprilia', 'RS 660'),
('Aprilia', 'RSV4'),
('Aprilia', 'Tuono 660'),
('Aprilia', 'Tuono V4'),
('Aprilia', 'Dorsoduro 900'),
('Aprilia', 'SMV 900'),
('Aprilia', 'SXV 550'),
('Aprilia', 'RS 125'),
('Aprilia', 'Shiver 900'),
('Aprilia', 'Mana 850'),
('MV Agusta', 'Brutale 800'),
('MV Agusta', 'F3 800'),
('MV Agusta', 'Turismo Veloce'),
('MV Agusta', 'Dragster 800'),
('MV Agusta', 'Brutale 1000'),
('MV Agusta', 'Superveloce 800'),
('MV Agusta', 'Rush 1000'),
('MV Agusta', 'Brutale 750'),
('MV Agusta', 'F4 1000'),
('MV Agusta', 'Stradale 800'),
('Moto Guzzi', 'V7'),
('Moto Guzzi', 'V85 TT'),
('Moto Guzzi', 'V9'),
('Moto Guzzi', 'California 1400'),
('Moto Guzzi', 'Audace'),
('Moto Guzzi', 'Griso 850'),
('Moto Guzzi', 'Eldorado'),
('Moto Guzzi', 'Breva 1200'),
('Moto Guzzi', 'Stelvio 1200'),
('Moto Guzzi', 'Nevada 750'),
('Husqvarna', 'Vitpilen 401'),
('Husqvarna', 'Svartpilen 401'),
('Husqvarna', 'Vitpilen 701'),
('Husqvarna', 'Svartpilen 701'),
('Husqvarna', '701 Enduro'),
('Husqvarna', 'TE 150'),
('Husqvarna', 'FC 250'),
('Husqvarna', 'FX 450'),
('Husqvarna', 'TX 300'),
('Husqvarna', 'FE 501'),
('Royal Enfield', 'Classic 350'),
('Royal Enfield', 'Bullet 350'),
('Royal Enfield', 'Himalayan'),
('Royal Enfield', 'Interceptor 650'),
('Royal Enfield', 'Continental GT 650'),
('Royal Enfield', 'Scram 411'),
('Royal Enfield', 'Hunter 350'),
('Royal Enfield', 'Meteor 350'),
('Royal Enfield', 'Super Meteor 650'),
('Royal Enfield', 'GT 650'),
('Hero MotoCorp', 'XPulse 200'),
('Hero MotoCorp', 'Impulse 200'),
('Hero MotoCorp', 'Destini 125'),
('Hero MotoCorp', 'Passion Pro'),
('Hero MotoCorp', 'HF Deluxe'),
('Hero MotoCorp', 'Splendor Plus'),
('Hero MotoCorp', 'Glamour'),
('Hero MotoCorp', 'Xtreme 160R'),
('Hero MotoCorp', 'Karizma XMR'),
('Hero MotoCorp', 'Lectro'),
('Bajaj', 'Pulsar 150'),
('Bajaj', 'Pulsar 250'),
('Bajaj', 'Dominar 400'),
('Bajaj', 'Avenger 160'),
('Bajaj', 'Avenger 220'),
('Bajaj', 'Avenger 250'),
('Bajaj', 'Chetak 150'),
('Bajaj', 'Freedom CNG'),
('Bajaj', 'Discover 125'),
('Bajaj', 'Platina 100'),
('TVS', 'Apache RTR 160'),
('TVS', 'Apache RTR 200'),
('TVS', 'Apache RR 310'),
('TVS', 'Raider 125'),
('TVS', 'Jupiter'),
('TVS', 'Scooty Pep Plus'),
('TVS', 'Max 125'),
('TVS', 'Dazz 110'),
('TVS', 'Ntorq 125'),
('TVS', 'Wego'),
('Jawa', 'Forty Two'),
('Jawa', 'Classic 300'),
('Jawa', 'Perak 300'),
('Jawa', 'Jawa 42'),
('Jawa', 'Jawa 300'),
('Jawa', 'Jawa Perak'),
('Jawa', 'Storm 125'),
('Jawa', 'Jawa 42 MM'),
('Jawa', 'TWO Wheeler'),
('Jawa', 'QUANTUM'),
('SYM', 'Crox 50'),
('SYM', 'Jet 50'),
('SYM', 'Orbit II 125'),
('SYM', 'Orbit III 125'),
('SYM', 'Symphony'),
('SYM', 'Fiddle 125'),
('SYM', 'Wolf 125'),
('SYM', 'HD 200'),
('SYM', 'VF 200'),
('SYM', 'T-Bird 200'),
('Benelli', 'TRK 502'),
('Benelli', 'Imperiale 400'),
('Benelli', 'BN600i'),
('Benelli', 'BN600'),
('Benelli', 'TNT 300'),
('Benelli', 'TNT 600'),
('Benelli', 'TNT 1130'),
('Benelli', 'Leoncino 500'),
('Benelli', 'Tornado 300'),
('Benelli', 'TRK 251'),
('Piaggio', 'MP3 300'),
('Piaggio', 'Beverly 300'),
('Piaggio', 'X7 300'),
('Piaggio', 'Liberty 125'),
('Piaggio', 'Carnaby 300'),
('Piaggio', 'Vespa 300'),
('Piaggio', 'Medley 150'),
('Piaggio', 'Typhoon 125'),
('Piaggio', 'Beverly 125'),
('Piaggio', 'X-Evo 125'),
('Peugeot', 'Metropolis 400'),
('Peugeot', 'Django 125'),
('Peugeot', 'TKR 125'),
('Peugeot', 'Speedfight 3'),
('Peugeot', 'Ludix 125'),
('Peugeot', 'Geo X'),
('Peugeot', 'Satelis 250'),
('Peugeot', 'Geopolis 300'),
('Peugeot', 'Tweet 125'),
('Peugeot', 'Vivacity 125'),
('Yamaha', 'TMAX 530'),
('Yamaha', 'NMax 155'),
('Yamaha', 'Aerox 155'),
('Yamaha', 'Mio 125'),
('Yamaha', 'Fino 125'),
('Yamaha', 'Freego 125'),
('Yamaha', 'Ray ZR 125'),
('Yamaha', 'FZ-S'),
('Yamaha', 'R15'),
('Yamaha', 'R3'),
('Honda', 'ADV 150'),
('Honda', 'Beat 110'),
('Honda', 'Vario 150'),
('Honda', 'Scoopy'),
('Honda', 'Ruckus'),
('Honda', 'Grom'),
('Honda', 'CBR1000RR-R'),
('Honda', 'CB1000R-F'),
('Honda', 'CRF450F'),
('Honda', 'XR150L'),
('Kawasaki', 'Ninja 1000SX'),
('Kawasaki', 'W800 Street'),
('Kawasaki', 'Ninja ZX-10R'),
('Kawasaki', 'KX250'),
('Kawasaki', 'KLX110R'),
('Kawasaki', 'KX85'),
('Kawasaki', 'KX450F'),
('Kawasaki', 'EX650'),
('Kawasaki', 'ZX6R'),
('Kawasaki', 'ZX14R'),
('Suzuki', 'GSX-S1000F'),
('Suzuki', 'Burgman 400'),
('Suzuki', 'Burgman 650'),
('Suzuki', 'Gixxer 155'),
('Suzuki', 'Gixxer SF 250'),
('Suzuki', 'Access 125'),
('Suzuki', 'Let\'s 125'),
('Suzuki', 'Intruder 150'),
('Suzuki', 'Intruder 250'),
('Suzuki', 'RM-Z450'),
('Ducati', 'Panigale 1299'),
('Ducati', 'Monster 1200'),
('Ducati', 'Hypermotard 821'),
('Ducati', 'Superbike 1098'),
('Ducati', 'Desmosedici'),
('Ducati', 'ST2'),
('Ducati', 'MH900e'),
('Ducati', 'Sport 1000'),
('Ducati', 'Paul Smart 1000'),
('Ducati', 'Senna'),
('KTM', 'RC 390'),
('KTM', 'RC 125'),
('KTM', 'RC 200'),
('KTM', '250 Adventure'),
('KTM', '125 Duke'),
('KTM', '200 Duke'),
('KTM', '390 Adventure'),
('KTM', '690 Enduro R'),
('KTM', '1290 Super Adventure'),
('KTM', '450 SMR');
