INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (1, 'Yamaha', 'MT-07');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (2, 'Yamaha', 'Tracer 9');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (3, 'Yamaha', 'XSR700');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (4, 'Yamaha', 'R1');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (5, 'Yamaha', 'Ténéré 700');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (6, 'Honda', 'CB650R');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (7, 'Honda', 'CBR500R');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (8, 'Honda', 'Africa Twin');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (9, 'Honda', 'Rebel 500');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (10, 'Honda', 'NC750X');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (11, 'Kawasaki', 'Z900');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (12, 'Kawasaki', 'Ninja 650');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (13, 'Kawasaki', 'Versys 650');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (14, 'Kawasaki', 'Z1000');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (15, 'Kawasaki', 'Vulcan S');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (16, 'Suzuki', 'GSX-S750');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (17, 'Suzuki', 'GSX-R1000');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (18, 'Suzuki', 'V-Strom 650');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (19, 'Suzuki', 'SV650');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (20, 'Suzuki', 'Hayabusa');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (21, 'BMW', 'R1250GS');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (22, 'BMW', 'S1000RR');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (23, 'BMW', 'F900R');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (24, 'BMW', 'R nineT');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (25, 'BMW', 'G310GS');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (26, 'Ducati', 'Monster 821');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (27, 'Ducati', 'Panigale V4');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (28, 'Ducati', 'Scrambler Icon');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (29, 'Ducati', 'Multistrada V4');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (30, 'Ducati', 'Diavel 1260');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (31, 'KTM', 'Duke 390');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (32, 'KTM', 'Duke 890');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (33, 'KTM', '1290 Super Duke R');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (34, 'KTM', '390 Adventure');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (35, 'KTM', '690 SMC R');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (36, 'Triumph', 'Street Triple 765');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (37, 'Triumph', 'Bonneville T120');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (38, 'Triumph', 'Tiger 900');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (39, 'Triumph', 'Speed Twin 900');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (40, 'Triumph', 'Rocket 3 R');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (41, 'Harley-Davidson', 'Iron 883');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (42, 'Harley-Davidson', 'Sportster S');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (43, 'Harley-Davidson', 'Street Bob');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (44, 'Harley-Davidson', 'Fat Boy 114');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (45, 'Harley-Davidson', 'Pan America 1250');

INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (46, 'Aprilia', 'RS 660');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (47, 'Aprilia', 'Tuono 660');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (48, 'Aprilia', 'Tuareg 660');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (49, 'Aprilia', 'RSV4 1100 Factory');
INSERT INTO VEHICULE (IDVEHICULE, MARQUE, MODELE) VALUES (50, 'Aprilia', 'SR GT 125');
